using System;
using System.Collections.Generic;
using System.Linq;
using Sungero.Core;
using Sungero.CoreEntities;
using Sungero.Metadata;
using Sungero.Domain.Shared;
using ReportRes = Auxo.Common.Reports.Resources;
using ReportConst = Auxo.Common.Constants.ObjectChanges;

namespace Auxo.Common
{
  partial class ObjectChangesServerHandlers
  {

    public override void BeforeExecute(Sungero.Reporting.Server.BeforeExecuteEventArgs e)
    {
      var objType = ObjectChanges.Entity;
      var handlerNames = this.GetEventNames();
      var reportSessionId = Guid.NewGuid().ToString();
      ObjectChanges.ReportSessionId = reportSessionId;

      var typeGuids = new List<string> { objType.EntityGuid };
      typeGuids.AddRange(objType.Parents.Select(_ => _.EntityGuid).ToList());
      foreach (var typeGuid in typeGuids)
      {
        var changedList = ObjectChangesDataReport(Guid.Parse(typeGuid), handlerNames);
        if (!changedList.Any())
          continue;
        
        foreach (var record in changedList)
          record.ReportSessionId = reportSessionId;
        
        Sungero.Docflow.PublicFunctions.Module.WriteStructuresToTable(ReportConst.SourceTableName, changedList);
      }
    }

    /// <summary>
    /// Получить данные для отчета "Изменения объекта".
    /// </summary>
    /// <param name="entityGuid">Guid метаданных объекта.</param>
    /// <param name="eventNames">Список событий и параметров.</param>
    /// <returns>Список измененных данных.</returns>
    [Public]
    public static List<Structures.ObjectChanges.IOverrideData> ObjectChangesDataReport(Guid entityGuid,
                                                                                       System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> handlerNames)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();
      
      var metadata = Sungero.Metadata.Services.MetadataSearcher.FindEntityMetadata(entityGuid);
      if (metadata == null)
        return changedList;
      
      //События
      changedList.AddRange(GetEditHandledEvents(metadata, handlerNames));
      
      //Свойства
      changedList.AddRange(GetEditProperties(metadata, handlerNames));
      
      //Действия
      changedList.AddRange(GetEditActions(metadata, handlerNames));
      
      //Форма
      changedList.AddRange(GetForms(metadata));
      
      //Лента
      changedList.AddRange(GetRibbons(metadata));
      
      if (!changedList.Any())
        return changedList;
      
      var moduleMetadata = metadata.ModuleMetadata;
      if (moduleMetadata != null)
      {
        foreach (var record in changedList)
          record.CompanyCode = moduleMetadata.CompanyCode;
      }
      
      return changedList;
    }
    
    /// <summary>
    /// Получить список измененных событий.
    /// </summary>
    /// <param name="metadata">Метаданные объекта.</param>
    /// <param name="handlerNames">Список событий и параметров.</param>
    /// <returns>Список измененных данных.</returns>
    private static List<Structures.ObjectChanges.IOverrideData> GetEditHandledEvents(Sungero.Metadata.EntityMetadata metadata,
                                                                                     System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> handlerNames)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();
      
      var excludeEvents = new List<string> { "IsAutoGenerated" };
      
      foreach (var handler in metadata.HandledEvents.Where(_ => !excludeEvents.Contains(_)))
      {
        var handlerName = handlerNames.Where(_ => _.Key == handler).FirstOrDefault();
        var itemName = handlerName.Value == null ? ResourceService.Instance.GetString(metadata, handler, true, Array.Empty<object>()) : handlerName.Value;
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.HandledEvents,
                                                                     itemName,
                                                                     string.Empty,
                                                                     ReportRes.ObjectChanges.RedefinedName,
                                                                     string.Empty));
      }

      foreach (var handler in metadata.OverriddenFields)
      {
        var handlerName = handlerNames.Where(_ => _.Key == handler).FirstOrDefault();
        var itemName = handlerName.Value == null ? ResourceService.Instance.GetString(metadata, handler, true, Array.Empty<object>()) : handlerName.Value;
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.HandledEvents,
                                                                     itemName,
                                                                     string.Empty,
                                                                     ReportRes.ObjectChanges.ModifiedName,
                                                                     string.Empty));
      }
      
      return changedList;
    }

    /// <summary>
    /// Получить список измененных свойств.
    /// </summary>
    /// <param name="metadata">Метаданные объекта.</param>
    /// <param name="eventNames">Список событий и параметров.</param>
    /// <returns>Список измененных данных.</returns>
    private static List<Structures.ObjectChanges.IOverrideData> GetEditProperties(Sungero.Metadata.EntityMetadata metadata,
                                                                                  System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> eventNames)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();
      
      if (metadata.Properties == null)
        return changedList;
      
      var baseMetadata = metadata.GetOriginal();
      if (metadata.NameGuid == baseMetadata.NameGuid)
        baseMetadata = metadata.BaseEntityMetadata;
      
      var iteration = 0;
      while (baseMetadata != null && baseMetadata.Properties == null && iteration < 5)
      {
        if (baseMetadata != null)
          baseMetadata = baseMetadata.BaseEntityMetadata;
        
        iteration++;
      }
      
      if (baseMetadata == null || baseMetadata.Properties == null)
        return changedList;

      //Найдем все новые свойства
      var properties = baseMetadata.Properties;
      List<string> basePropertiesNames = properties.Select(_ => _.Name).ToList();
      foreach (var propertyMetadata in metadata.Properties.Where(_ => !basePropertiesNames.Contains(_.Name)))
      {
        var collectionName = propertyMetadata.PropertyType == Sungero.Metadata.PropertyType.Collection ? ReportRes.ObjectChanges.CollectionName : string.Empty;
        var propertyName = ReportRes.ObjectChanges.CollectionFormatFormat(collectionName, propertyMetadata.GetLocalizedName(), propertyMetadata.Name);
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.Properties,
                                                                     propertyName,
                                                                     string.Empty,
                                                                     ReportRes.ObjectChanges.AddedName,
                                                                     string.Empty));
      }
      
      //Найдем все измененные свойства
      foreach (var propertyMetadata in metadata.Properties.Where(_ => _.IsOverridden))
      {
        var propertyName = ReportRes.ObjectChanges.PropertyFormatFormat(propertyMetadata.GetLocalizedName(), propertyMetadata.Name);
        GetEditProperty(changedList, propertyName, propertyMetadata, eventNames);
      }

      //Перекрытые свойства коллекций
      foreach (Sungero.Metadata.CollectionPropertyMetadata collectionMetadata in metadata.Properties.Where(_ => _.PropertyType == Sungero.Metadata.PropertyType.Collection))
      {
        var baseCollectionMetadata = (Sungero.Metadata.CollectionPropertyMetadata)metadata.BaseEntityMetadata.Properties.FirstOrDefault(_ => _.Name == collectionMetadata.Name);
        if (baseCollectionMetadata != null)
        {
          var basCollectionNames = baseCollectionMetadata.InterfaceMetadata.Properties.Select(_ => _.Name).ToList();
          foreach (var propertyMetadata in collectionMetadata.InterfaceMetadata.Properties.Where(_ => !basCollectionNames.Contains(_.Name)))
          {
            var propertyName = ReportRes.ObjectChanges.PropertyCollectionFormat(propertyMetadata.GetLocalizedName(), propertyMetadata.Name, collectionMetadata.GetLocalizedName(), collectionMetadata.Name);
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Properties,
                                                                         propertyName,
                                                                         string.Empty,
                                                                         ReportRes.ObjectChanges.AddedName,
                                                                         string.Empty));
          }
        }

        foreach (var propertyMetadata in collectionMetadata.InterfaceMetadata.Properties.Where(_ => _.IsOverridden))
        {
          var propertyName = ReportRes.ObjectChanges.PropertyCollectionFormat(propertyMetadata.GetLocalizedName(), propertyMetadata.Name, collectionMetadata.GetLocalizedName(), collectionMetadata.Name);
          GetEditProperty(changedList, propertyName, propertyMetadata, eventNames);
        }
      }
      
      return changedList;
    }
    
    /// <summary>
    /// Получить список измененных данных свойства.
    /// </summary>
    /// <param name="changedList">Список измененных событий.</param>
    /// <param name="propertyName">Имя свойства.</param>
    /// <param name="propertyMetadata">Метаданные свойства.</param>
    /// <param name="eventNames">Список событий и параметров.</param>
    private static void GetEditProperty(List<Structures.ObjectChanges.IOverrideData> changedList,
                                        string propertyName,
                                        Sungero.Metadata.PropertyMetadata propertyMetadata,
                                        System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> eventNames)
    {
      foreach (var handler in propertyMetadata.HandledEvents)
      {
        var eventName = eventNames.Where(_ => _.Key == handler).FirstOrDefault();
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.Properties,
                                                                     propertyName,
                                                                     !Equals(eventName.Value, null) ? eventName.Value : handler,
                                                                     ReportRes.ObjectChanges.RedefinedName,
                                                                     string.Empty));
      }
      
      var excludeFields = new List<string> {
        "EntityGuid",
        "HandledEvents",
        "Values",
        "PreviousPropertyGuid",
        "IsVisibleInCollectionByDefault",
        "IsVisibleInFolderByDefault",
        "NeedPassEntityToLookupEvent",
        "IsAutoGenerated"
      };
      
      foreach (var field in propertyMetadata.OverriddenFields.Where(_ => !excludeFields.Contains(_)))
      {
        var fieldName = eventNames.Where(_ => _.Key == field).FirstOrDefault();
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.Properties,
                                                                     propertyName,
                                                                     !Equals(fieldName.Value, null) ? fieldName.Value : field,
                                                                     ReportRes.ObjectChanges.ModifiedName,
                                                                     string.Empty));
      }
      
      if (propertyMetadata.PropertyType == Sungero.Metadata.PropertyType.Enumeration)
      {
        var enumMetadata = (Sungero.Metadata.EnumPropertyMetadata)propertyMetadata;
        if (enumMetadata.DirectValues != null && enumMetadata.DirectValues.Any())
          changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                       ReportConst.ChaptersNames.Properties,
                                                                       propertyName,
                                                                       string.Empty,
                                                                       ReportRes.ObjectChanges.AddedEnumsName,
                                                                       string.Empty));
      }
    }
    
    /// <summary>
    /// Получить список измененных действий.
    /// </summary>
    /// <param name="metadata">Метаданные объекта.</param>
    /// <param name="handlerNames">Список событий и параметров.</param>
    /// <returns>Список измененных данных.</returns>
    private static List<Structures.ObjectChanges.IOverrideData> GetEditActions(Sungero.Metadata.EntityMetadata metadata,
                                                                               System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> handlerNames)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();

      if (metadata.Actions == null)
        return changedList;
      
      var baseMetadata = metadata.GetOriginal();
      if (metadata.NameGuid == baseMetadata.NameGuid)
        baseMetadata = metadata.BaseEntityMetadata;
      
      var iteration = 0;
      while (baseMetadata != null && baseMetadata.Actions == null && iteration < 5)
      {
        if (baseMetadata != null)
          baseMetadata = baseMetadata.BaseEntityMetadata;
        
        iteration++;
      }
      
      if (baseMetadata == null || baseMetadata.Actions == null)
        return changedList;
      
      //Найдем все новые действия
      var actions = baseMetadata.Actions;
      List<string> baseActionsNames = actions.Select(_ => _.Name).ToList();
      foreach (var actionMetadata in metadata.Actions.Where(_ => !baseActionsNames.Contains(_.Name)))
      {
        var actionName = ReportRes.ObjectChanges.ActionFormatFormat(actionMetadata.GetLocalizedName(), actionMetadata.Name);
        changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                     ReportConst.ChaptersNames.Actions,
                                                                     actionName,
                                                                     string.Empty,
                                                                     ReportRes.ObjectChanges.AddedName,
                                                                     string.Empty));
      }
      
      //Найдем все измененные действия
      foreach (var actionMetadata in metadata.Actions.Where(_ => _.IsOverridden))
      {
        var actionName = ReportRes.ObjectChanges.ActionFormatFormat(actionMetadata.GetLocalizedName(), actionMetadata.Name);
        foreach (var field in actionMetadata.OverriddenFields)
        {
          var fieldName = handlerNames.Where(_ => _.Key == field).FirstOrDefault();
          var itemName = fieldName.Value == null ? ResourceService.Instance.GetString(metadata, field, true, Array.Empty<object>()) : fieldName.Value;
          changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                       ReportConst.ChaptersNames.Actions,
                                                                       actionName,
                                                                       itemName,
                                                                       ReportRes.ObjectChanges.ModifiedName,
                                                                       string.Empty));
        }
      }
      
      return changedList;
    }
    
    /// <summary>
    /// Получить список контролов формы.
    /// </summary>
    /// <param name="metadata">Метаданные объекта.</param>
    /// <returns>Список измененных данных.</returns>
    private static List<Structures.ObjectChanges.IOverrideData> GetForms(Sungero.Metadata.EntityMetadata metadata)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();

      if (metadata.SerializableForms == null)
        return changedList;
      
      var baseMetadata = metadata.GetOriginal();
      if (metadata.NameGuid == baseMetadata.NameGuid)
        baseMetadata = metadata.BaseEntityMetadata;
      
      var iteration = 0;
      while (baseMetadata != null && baseMetadata.SerializableForms == null && iteration < 5)
      {
        if (baseMetadata != null)
          baseMetadata = baseMetadata.BaseEntityMetadata;
        
        iteration++;
      }
      
      if (baseMetadata == null || baseMetadata.SerializableForms == null)
        return changedList;

      var serializableForms = baseMetadata.SerializableForms;
      List<string> baseFormsNames = serializableForms.Select(_ => _.Name).ToList();
      foreach (var formMetadata in metadata.SerializableForms
               .Where(_ => _ is Sungero.Metadata.InplaceFormMetadata)
               .Where(_ => !baseFormsNames.Contains(_.Name) || _.IsOverridden))
      {
        var action = formMetadata.IsOverridden ? ReportRes.ObjectChanges.ModifiedName : ReportRes.ObjectChanges.AddedName;
        var resourceFormName = ReportRes.ObjectChanges.ResourceName_FormFormat(formMetadata.NameGuid.ToString().Replace("-", string.Empty));
        var formName = ResourceService.Instance.GetString(formMetadata.ParentEntityMetadata, resourceFormName, true, Array.Empty<object>());
        var pageName = ReportRes.ObjectChanges.PageNameFormat(formName, formMetadata.Name);
        foreach (var controlMetadata in formMetadata.Controls)
        {
          //Группа контролов
          if (controlMetadata is Sungero.Metadata.ControlGroupMetadata)
          {
            var groupCntrl = (Sungero.Metadata.ControlGroupMetadata)controlMetadata;
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.GroupNameFormat(groupCntrl.GetDisplayName(), groupCntrl.Name),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
            continue;
          }
          
          if (controlMetadata is Sungero.Metadata.ControlMetadata)
          {
            var control = (Sungero.Metadata.ControlMetadata)controlMetadata;
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.ControlNameFormat(control.Property.GetLocalizedName(), control.Name),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
            continue;
          }
          
          if (controlMetadata is Sungero.Metadata.HyperlinkControlMetadata)
          {
            var hyperlink = (Sungero.Metadata.HyperlinkControlMetadata)controlMetadata;
            var resourceName = ReportRes.ObjectChanges.ResourceName_ControlFormat(hyperlink.NameGuid.ToString().Replace("-", string.Empty));
            var hyperlinkName = ResourceService.Instance.GetString(hyperlink.ParentFormMetadata.ParentEntityMetadata, resourceName, true, Array.Empty<object>());
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.LinkNameFormat(hyperlinkName, hyperlink.FunctionName),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
            continue;
          }
          
          if (controlMetadata is Sungero.Metadata.FunctionControlMetadata)
          {
            var function = (Sungero.Metadata.FunctionControlMetadata)controlMetadata;
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.StateViewNameFormat(function.Name, function.FunctionName),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
            continue;
          }
          
          if (controlMetadata is Sungero.Metadata.PreviewControlMetadata)
          {
            var preview = (Sungero.Metadata.PreviewControlMetadata)controlMetadata;
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.PreviewNameFormat(preview.Name),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
            continue;
          }

          if (controlMetadata is Sungero.Metadata.LabelControlMetadata)
          {
            var label = (Sungero.Metadata.LabelControlMetadata)controlMetadata;
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.Forms,
                                                                         ReportRes.ObjectChanges.LabelNameFormat(label.Property.GetLocalizedName(), label.Name),
                                                                         pageName,
                                                                         action,
                                                                         string.Empty));
          }
        }
      }
      
      
      return changedList;
    }
    
    /// <summary>
    /// Получить список контролов ленты.
    /// </summary>
    /// <param name="metadata">Метаданные объекта.</param>
    /// <returns>Список измененных данных.</returns>
    private static List<Structures.ObjectChanges.IOverrideData> GetRibbons(Sungero.Metadata.EntityMetadata metadata)
    {
      var changedList = new List<Structures.ObjectChanges.IOverrideData>();
      
      if (metadata.RibbonCardMetadata == null)
        return changedList;
      
      var baseMetadata = metadata.GetOriginal();
      if (metadata.NameGuid == baseMetadata.NameGuid)
        baseMetadata = metadata.BaseEntityMetadata;
      
      var iteration = 0;
      while (baseMetadata != null && baseMetadata.RibbonCardMetadata == null && iteration < 5)
      {
        if (baseMetadata != null)
          baseMetadata = baseMetadata.BaseEntityMetadata;
        
        iteration++;
      }
      
      if (baseMetadata == null || baseMetadata.RibbonCardMetadata == null)
        return changedList;

      var ribbonCardMetadata = baseMetadata.RibbonCardMetadata;
      List<string> baseRibbonNames = ribbonCardMetadata.AllElements.Select(_ => _.Name).ToList();
      foreach (var groupMetadata in metadata.RibbonCardMetadata.AllElements.Where(_ => !baseRibbonNames.Contains(_.Name) || _.IsOverridden).GroupBy(_ => _.ParentGroup.ParentPage))
      {
        var pageMetadata = (Sungero.Metadata.RibbonPageMetadata)groupMetadata.Key;
        var pageResourceName = ReportRes.ObjectChanges.ResourceName_RibbonFormat(pageMetadata.Name, pageMetadata.NameGuid.ToString().Replace("-", string.Empty));
        var groupName = ReportRes.ObjectChanges.TabNameFormat(ResourceService.Instance.GetString(metadata, pageResourceName, true, Array.Empty<object>()));
        foreach (var actionMetadata in groupMetadata)
        {
          var actionName = string.Empty;
          
          if (actionMetadata is Sungero.Metadata.RibbonActionButtonMetadata)
          {
            var ribbonAction = (Sungero.Metadata.RibbonActionButtonMetadata)actionMetadata;
            actionName = ReportRes.ObjectChanges.ActionNameFormat(ribbonAction.Action.GetLocalizedName());
          }
          
          if (actionMetadata is Sungero.Metadata.RibbonStateToggleButtonMetadata)
          {
            var stateToggle = (Sungero.Metadata.RibbonStateToggleButtonMetadata)actionMetadata;
            var stateToggleResourceName = ReportRes.ObjectChanges.ResourceName_RibbonFormat(stateToggle.Name, stateToggle.NameGuid.ToString().Replace("-", string.Empty));
            actionName = ReportRes.ObjectChanges.SwitchNameFormat(ResourceService.Instance.GetString(metadata, stateToggleResourceName, true, Array.Empty<object>()));
          }
          
          if (actionMetadata is Sungero.Metadata.RibbonStaticDropDownButtonMetadata)
          {
            var dropDownButton = (Sungero.Metadata.RibbonStaticDropDownButtonMetadata)actionMetadata;
            var dropDownResourceName = ReportRes.ObjectChanges.ResourceName_RibbonFormat(dropDownButton.Name, dropDownButton.NameGuid.ToString().Replace("-", string.Empty));
            actionName = ReportRes.ObjectChanges.MenuButtonNameFormat(ResourceService.Instance.GetString(metadata, dropDownResourceName, true, Array.Empty<object>()));
          }
          
          if (actionMetadata is Sungero.Metadata.RibbonToggleButtonMetadata)
          {
            var toggleButton = (Sungero.Metadata.RibbonToggleButtonMetadata)actionMetadata;
            actionName = ReportRes.ObjectChanges.PropertySwitchNameFormat(toggleButton.Action.GetLocalizedName());
          }
          
          if (!string.IsNullOrEmpty(actionName))
            changedList.Add(Structures.ObjectChanges.OverrideData.Create(string.Empty,
                                                                         ReportConst.ChaptersNames.RibbonActions,
                                                                         actionName,
                                                                         groupName,
                                                                         actionMetadata.IsOverridden ? ReportRes.ObjectChanges.ModifiedName : ReportRes.ObjectChanges.AddedName,
                                                                         string.Empty));
        }
      }
      
      return changedList;
    }
    
    /// <summary>
    /// Получить список событий и параметров.
    /// </summary>
    /// <returns>Список событий и параметров.</returns>
    public virtual System.Collections.Generic.HashSet<System.Collections.Generic.KeyValuePair<string, string>> GetEventNames()
    {
      return new HashSet<KeyValuePair<string, string>> {
        new KeyValuePair<string, string> ("BeforeSaveServer", ReportRes.ObjectChanges.Event_BeforeSaveServer),
        new KeyValuePair<string, string> ("SavingServer", ReportRes.ObjectChanges.Event_SavingServer),
        new KeyValuePair<string, string> ("SavedServer", ReportRes.ObjectChanges.Event_SavedServer),
        new KeyValuePair<string, string> ("AfterSaveServer", ReportRes.ObjectChanges.Event_AfterSaveServer),
        new KeyValuePair<string, string> ("WriteHistoryServer", ReportRes.ObjectChanges.Event_WriteHistoryServer),
        new KeyValuePair<string, string> ("BeforeDeleteServer", ReportRes.ObjectChanges.Event_BeforeDeleteServer),
        new KeyValuePair<string, string> ("DeletingServer", ReportRes.ObjectChanges.Event_DeletingServer),
        new KeyValuePair<string, string> ("AfterDeleteServer", ReportRes.ObjectChanges.Event_AfterDeleteServer),
        new KeyValuePair<string, string> ("CreatingFromServer", ReportRes.ObjectChanges.Event_CreatingFromServer),
        new KeyValuePair<string, string> ("CreatedServer", ReportRes.ObjectChanges.Event_CreatedServer),
        new KeyValuePair<string, string> ("FilteringServer", ReportRes.ObjectChanges.Event_FilteringServer),
        new KeyValuePair<string, string> ("ValidateFilterPanelClient", ReportRes.ObjectChanges.Event_ValidateFilterPanelClient),
        new KeyValuePair<string, string> ("UiFilteringServer", ReportRes.ObjectChanges.Event_UiFilteringServer),
        new KeyValuePair<string, string> ("ShowingClient", ReportRes.ObjectChanges.Event_ShowingClient),
        new KeyValuePair<string, string> ("ClosingClient", ReportRes.ObjectChanges.Event_ClosingClient),
        new KeyValuePair<string, string> ("RefreshClient", ReportRes.ObjectChanges.Event_RefreshClient),
        new KeyValuePair<string, string> ("ChangedShared", ReportRes.ObjectChanges.Event_ChangedShared),
        new KeyValuePair<string, string> ("AddedShared", ReportRes.ObjectChanges.Event_AddedShared),
        new KeyValuePair<string, string> ("DeletedShared", ReportRes.ObjectChanges.Event_DeletedShared),
        new KeyValuePair<string, string> ("ValueInputClient", ReportRes.ObjectChanges.Event_ValueInputClient),        
        new KeyValuePair<string, string> ("IsRequired", ReportRes.ObjectChanges.Event_IsRequired),        
        new KeyValuePair<string, string> ("IsEnabled", ReportRes.ObjectChanges.Event_IsEnabled),
        new KeyValuePair<string, string> ("IsShowedInList", ReportRes.ObjectChanges.Event_IsShowedInList),
        new KeyValuePair<string, string> ("CanBeSearch", ReportRes.ObjectChanges.Event_CanBeSearch),
        new KeyValuePair<string, string> ("IsVisibility", ReportRes.ObjectChanges.Event_IsVisibility),
        new KeyValuePair<string, string> ("IsLoadEagerly", ReportRes.ObjectChanges.Event_IsLoadEagerly),
        new KeyValuePair<string, string> ("IsUnique", ReportRes.ObjectChanges.Event_IsUnique),
        new KeyValuePair<string, string> ("IsDisplayValue", ReportRes.ObjectChanges.Event_IsDisplayValue),
        new KeyValuePair<string, string> ("IsQuickSearchAllowed", ReportRes.ObjectChanges.Event_IsQuickSearchAllowed),
        new KeyValuePair<string, string> ("GenerateHandler", ReportRes.ObjectChanges.Event_GenerateHandler),
        new KeyValuePair<string, string> ("NeedConfirmation", ReportRes.ObjectChanges.Event_NeedConfirmation),
        new KeyValuePair<string, string> ("AllowUserDisableConfirmation", ReportRes.ObjectChanges.Event_AllowUserDisableConfirmation),
        new KeyValuePair<string, string> ("IsToggleAction", ReportRes.ObjectChanges.Event_IsToggleAction),
        new KeyValuePair<string, string> ("IsEmptySelectionAllowed", ReportRes.ObjectChanges.Event_IsEmptySelectionAllowed),
        new KeyValuePair<string, string> ("IsCreationAction", ReportRes.ObjectChanges.Event_IsCreationAction),
        new KeyValuePair<string, string> ("SmallIconName", ReportRes.ObjectChanges.Event_SmallIconName),
        new KeyValuePair<string, string> ("LargeIconName", ReportRes.ObjectChanges.Event_LargeIconName),
        new KeyValuePair<string, string> ("IsVisible", ReportRes.ObjectChanges.Event_IsVisible),
        new KeyValuePair<string, string> ("CanBeSearch", ReportRes.ObjectChanges.Event_CanBeSearch),
        new KeyValuePair<string, string> ("IconName", ReportRes.ObjectChanges.Event_IconName),
        new KeyValuePair<string, string> ("HideFromCreationArea", ReportRes.ObjectChanges.Event_HideFromCreationArea),
        new KeyValuePair<string, string> ("HideFromNavigationEditorCreationArea", ReportRes.ObjectChanges.Event_HideFromNavigationEditorCreationArea),
        new KeyValuePair<string, string> ("ShowingSignDialogClient", ReportRes.ObjectChanges.Event_ShowingSignDialogClient),
        new KeyValuePair<string, string> ("LookupMode", ReportRes.ObjectChanges.Event_LookupMode),
        new KeyValuePair<string, string> ("IsCacheable", ReportRes.ObjectChanges.Event_IsCacheable),
        new KeyValuePair<string, string> ("OpenCardByDefaultInCollection", ReportRes.ObjectChanges.Event_OpenCardByDefaultInCollection),
        new KeyValuePair<string, string> ("IsAutoCreated", ReportRes.ObjectChanges.Event_IsAutoCreated),
        new KeyValuePair<string, string> ("NeedWriteHistory", ReportRes.ObjectChanges.Event_NeedWriteHistory),
        new KeyValuePair<string, string> ("CanBeUsedInIntegration", ReportRes.ObjectChanges.Event_CanBeUsedInIntegration),
        new KeyValuePair<string, string> ("IsStatusEnabled", ReportRes.ObjectChanges.Event_IsStatusEnabled),
        new KeyValuePair<string, string> ("SearchDialogLookupServer", ReportRes.ObjectChanges.Event_SearchDialogLookupServer),
        new KeyValuePair<string, string> ("LookupServer", ReportRes.ObjectChanges.Event_LookupServer),
        new KeyValuePair<string, string> ("FlatListInStandaloneLookup", ReportRes.ObjectChanges.Event_FlatListInStandaloneLookup),
        new KeyValuePair<string, string> ("ConvertingFromServer", ReportRes.ObjectChanges.Event_ConvertingFromServer),
        new KeyValuePair<string, string> ("BeforeSigningServer", ReportRes.ObjectChanges.Event_BeforeSigningServer),
        new KeyValuePair<string, string> ("BeforeStartServer", ReportRes.ObjectChanges.Event_BeforeStartServer),
        new KeyValuePair<string, string> ("BeforeRestartServer", ReportRes.ObjectChanges.Event_BeforeRestartServer),
        new KeyValuePair<string, string> ("BeforeResumeServer", ReportRes.ObjectChanges.Event_BeforeResumeServer),
        new KeyValuePair<string, string> ("BeforeAbortServer", ReportRes.ObjectChanges.Event_BeforeAbortServer),
        new KeyValuePair<string, string> ("AfterSuspendServer", ReportRes.ObjectChanges.Event_AfterSuspendServer),
        new KeyValuePair<string, string> ("OnlyPerformersCanComplete", ReportRes.ObjectChanges.Event_OnlyPerformersCanComplete),
        new KeyValuePair<string, string> ("ShowTypeNameInThread", ReportRes.ObjectChanges.Event_ShowTypeNameInThread),
        new KeyValuePair<string, string> ("IsCreateVersionsOnLayerForbidden", ReportRes.ObjectChanges.Event_IsCreateVersionsOnLayerForbidden),
        new KeyValuePair<string, string> ("DocumentVersionCreationSources", ReportRes.ObjectChanges.Event_DocumentVersionCreationSources),
        new KeyValuePair<string, string> ("UseSchemeFromSettings", ReportRes.ObjectChanges.Event_UseSchemeFromSettings),
        new KeyValuePair<string, string> ("EntityAfterSuspendEvent", ReportRes.ObjectChanges.Event_EntityAfterSuspendEvent),
        new KeyValuePair<string, string> ("EntityBeforeAbortEvent", ReportRes.ObjectChanges.Event_EntityBeforeAbortEvent),
        new KeyValuePair<string, string> ("EntityBeforeResumeEvent", ReportRes.ObjectChanges.Event_EntityBeforeResumeEvent)
      };
    }
    
    public override void AfterExecute(Sungero.Reporting.Server.AfterExecuteEventArgs e)
    {
      Sungero.Docflow.PublicFunctions.Module.DeleteReportData(ReportConst.SourceTableName, ObjectChanges.ReportSessionId);
    }

  }
}